# Generated by Django 5.0.6 on 2024-06-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(default='https://www.youtube.com/watch?v=dQw4w9WgXcQ'),
        ),
    ]
