# Generated by Django 5.0.6 on 2024-06-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_course_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.TextField(default='Python'),
        ),
    ]
